### ISSUE TITLE
Provide multiple scripts?

### ISSUE THREAD

**Issue by nickjer** [OSC/ood_auth_map#1]
Currently the main CLI scans a `grid-mapfile` installed on the system for the corresponding user mapping.  Should we instead provide multiple scripts that the sys admin can choose from or use as examples to build their own?

E.g.:
- `ood_auth_map.grid-mapfile`
- `ood_auth_map.regex`
- `ood_auth_map.echo`

Benefit of this is that it is easy to plug in a different user mapping script for a given OOD Portal. Cons are that we will have an explosion of scripts.

I am also open to other ideas. This needs to be decided on soon as we will be using a Shib IdP for the AweSim spin-up.

Thoughts: @basilgohar and @ericfranz

**Comment by ericfranz** [comment]
If we provide multiple scripts, is it a requirement that these be written in ruby?

**Comment by nickjer** [comment]
No, they can be any language that the center supports.

**Comment by nickjer** [comment]
Fixed here: 1ef64d0cd5c4d5367bf7db391c44b1a001195503
